name: Monitor Website Changes

on:
  schedule:
    - cron: '*/1 * * * *'  # Uruchamianie co minutę
  workflow_dispatch:  # Możliwość ręcznego uruchomienia

permissions:
  contents: write  # Pozwala na zapisywanie zmian w repozytorium

jobs:
  check_website:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzenie kodu repozytorium
        uses: actions/checkout@v3  # Pobiera najnowsze pliki z repo

      - name: Instalacja zależności Pythona
        run: pip install requests beautifulsoup4

      - name: Uruchomienie skryptu monitorującego
        run: python kod.py

      - name: Commit zmian jeśli wykryto różnice
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add changes.txt cache.txt
          git diff --cached --exit-code || (git commit -m "📌 Wykryto zmianę na stronie!" && git push)

      - name: Wysłanie e-maila, jeśli wykryto zmianę
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_SENDER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🔴 Wykryto zmianę na stronie!"
          body: "Strona zmieniła się! Oto różnice:\n\n$(cat changes.txt)"
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: "Monitor Strony <${{ secrets.EMAIL_SENDER }}>"
