name: Monitor PDF Count

on:
  schedule:
    - cron: '*/1 * * * *'  # Sprawdza stronę co minutę
  workflow_dispatch:  # Możliwość ręcznego uruchomienia

permissions:
  contents: write  # Pozwala na commitowanie zmian

jobs:
  check_website:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v3  # Pobiera pliki repozytorium

      - name: Instalacja zależności Pythona
        run: pip install requests beautifulsoup4

      - name: Uruchomienie skryptu sprawdzającego PDF-y
        run: python kod.py

      - name: Commit zmian jeśli wykryto różnice
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add changes.txt cache.txt
          git diff --cached --exit-code || (git commit -m "📌 Wykryto zmianę w liczbie 'pdf'!" && git push)

      - name: Wysłanie e-maila, jeśli wykryto zmianę
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_SENDER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🔴 Wykryto zmianę w PDF-ach!"
          body: "Liczba 'pdf' na stronie się zmieniła!\n\n$(cat changes.txt)"
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: "Monitor Strony <${{ secrets.EMAIL_SENDER }}>"
